### ISSUE TITLE
win10 show desktop problem

### ISSUE THREAD

**Issue by gevv** [cdhigh/sprintFontRelease#1]
Hello, 

When the sprint layout and sprintFont are open and show the desktop, the sprint layout window does not return.

https://user-images.githubusercontent.com/5096676/172142215-c9ddc2fa-1dd7-4e7c-91fb-558e0e56ddf9.mp4

**Comment by cdhigh** [comment]
It is not a bug.
This is how the sprint-layout plugin system works,
When you start the plugin, sprint-layout creates a child process, let the plugin running in the child process, and suspends itself, waiting until the child process returns.

**Comment by gevv** [comment]
I understood thanks
