### ISSUE TITLE
1.5.3 for XP目前发现泪滴功能有问题，能否更新一下支持XP的版本？

### ISSUE THREAD

**Issue by ihidao** [cdhigh/sprintFontRelease#10]
1.5.3 for XP目前发现泪滴功能有问题，选中焊盘时不能创建，不选中则会将所有焊盘都加泪滴，而且泪滴不露铜，这样焊的时候上不了锡等于没用

主要是有些古董电脑配置很低装的XP又不能升级，如果有可能考虑更新一下，谢谢

**Comment by cdhigh** [comment]
1. 如果要创建部分泪滴，需要选中焊盘和导线，不能只选择焊盘；
2. 我记得以前我看到过实际的泪滴焊盘，是不露铜的，泪滴焊盘不是为焊接多沾锡，而是保护焊盘更好的附着在基板上；
3. 什么时候我再装一次虚拟机升级一次xp版本

**Comment by ihidao** [comment]
> * 的附着在基板上；
> * 什么时候我再装一次虚拟机升级一次xp版本

1.同时选中焊盘和导线创建泪滴成功了
2.我是门外汉，才开始学画的，对这些不懂，不过在网上下载了一个资料上说泪滴要露铜
![hidao org_2024-12-18_12-52-42](https://github.com/user-attachments/assets/4da888b5-ff6e-4bd3-8c48-8f174e217353)
3.今天发现从立创导的焊盘和立创里有差异，比如：C22383472的孔
![hidao org_2024-12-18_12-44-52](https://github.com/user-attachments/assets/b61fe0ca-5790-41cf-ac3d-9e88be6bf7ea)
![hidao org_2024-12-18_12-45-9](https://github.com/user-attachments/assets/06ae4b2d-ea0e-4e9b-a9ef-8cbc739e8c63)

**Comment by ihidao** [comment]
刚试了下立创EDA，发现泪滴也是不露铜的：
![hidao org_2024-12-18_13-17-36](https://github.com/user-attachments/assets/71bee8ad-ac99-47f2-92d8-63f5353dc0a1)

**Comment by cdhigh** [comment]
软件不是一一对应的，sprintlayout里面没有圆角矩形的焊孔

**Comment by cdhigh** [comment]
已经更新windows xp为最新版本
