### ISSUE TITLE
Vir..s alert

### ISSUE THREAD

**Issue by gevv** [cdhigh/sprintFontRelease#2]
Hi,

v1.3 gives vir..s warning  (nod 32 current database 13.06.2022)

https://bit.ly/3mFZZSE

`<html><body>

Category | vir..s
-- | --
Size | 78279 B
Aliases | Vir..s.Win32.Pioneer.cz (Kaspersky)
  | W32.Fixflo.B!inf (Symantec)
  | Win32.FloodFix.7 (Dr.Web)
  | Virus:Win32/Floxif.H (Microsoft)

</body>
</html>`

**Comment by cdhigh** [comment]
This is false positive of Nod32.

The result from VirusTotal site:
https://www.virustotal.com/gui/file/2ca7ecbda650c1a0dde105313298d1477d5fe8d3b3f56a15b978ef693daee243
![virustotal_sprintfont](https://user-images.githubusercontent.com/2580077/173404312-54edaf12-6ace-4834-ad2d-2ba9ebd84ad9.png)

sprintFont is developed by using language Python, packaged by cx_freeze, perhaps the reason of cxfreeze packaged.

**Comment by cdhigh** [comment]
I confirmed again, yes, the python37.dll is infected.
I packed the v1.3 in other computer, you can download again and test it now.

**Comment by gevv** [comment]
Thanks a lot, problem solved.

Best regards.
