### ISSUE TITLE
Feature request "Rounded tracks"

### ISSUE THREAD

**Issue by gevv** [cdhigh/sprintFontRelease#3]
Hello,

Can the "Rounded tracks" feature be added? 

Thanks.

Best regards.

**Comment by cdhigh** [comment]
Can you describe requirements in detail, for example how to operate and what to achieve, etc

**Comment by gevv** [comment]
After the plugin is run 

Can be rounded with a mouse click

![sample](https://user-images.githubusercontent.com/5096676/179304754-4f889826-6b45-42aa-9ca1-178cd9f8f583.png)

_setting options for rounding rate would be nice too_

Thanks.

**Comment by cdhigh** [comment]
The Sprint-Layout plugin system/nterface are relatively elementary and have no realtime interaction ability. It communicates with the plugin through temporary files. When the plugin is running, the main program is suspended.
 So the scene is:
 You select several tracks, execute the plugin, and convert them to rounded tracks. If there are different rouned tracks with different parameters, you need to execute the plugin multiple times.
Is it acceptable?

**Comment by cdhigh** [comment]
I found a video:
https://www.youtube.com/watch?v=0VQFfilsr4c&ab_channel=DrewFustini
This feature is awesome but it cannot be implemented in plugin of Sprint-Layout
If Sprint-Layout can add a IPC (Inter-Process Communication) to plugin system, This feature may become reality.

**Comment by gevv** [comment]
`The Sprint-Layout plugin system/nterface are relatively elementary and have no realtime interaction ability. It communicates with the plugin through temporary files. When the plugin is running, the main program is suspended.
So the scene is:
You select several tracks, execute the plugin, and convert them to rounded tracks. If there are different rouned tracks with different parameters, you need to execute the plugin multiple times.
Is it acceptable?`

Best method for now. As you said, the sprint layout is limited.

_I'll make a request for the ipc I hope abacom takes care of it._

Thanks.

**Comment by cdhigh** [comment]
v1.5 added feature of Rounded-track
