### ISSUE TITLE
No fonts

### ISSUE THREAD

**Issue by Schumi402** [cdhigh/sprintFontRelease#4]
Installed fonts are not displayed in the list, there are only system fonts.

**Comment by cdhigh** [comment]
Only display fonts in directory "c:\windows\fonts" and SprintFont directory.
Can support ttf/otf/ttc/otf format.

**Comment by Schumi402** [comment]
Yes, format ttf, is in directory "c:\windows\fonts" but not displayed in the list sprintFont

**Comment by Schumi402** [comment]
I copied the font files to directory SprintFont. It works. Thank.

**Comment by cdhigh** [comment]
This problem has been fixed in v1.5.2.
