### ISSUE TITLE
 sprintFont_v1.5.2

### ISSUE THREAD

**Issue by maksland** [cdhigh/sprintFontRelease#5]
Good afternoon!
Is it possible to add the manufacture of oval holes ?
[oval.zip](https://github.com/cdhigh/sprintFontRelease/files/12331762/oval.zip)

**Comment by cdhigh** [comment]
In this scenario, I believe that creating a macro (component) and saving it in the library would be an acceptable solution?

**Comment by gevv** [comment]
Hi, @maksland     I create and use macros. pcb manufacturers operate as in the picture you gave for example.

![Untitled 1](https://github.com/cdhigh/sprintFontRelease/assets/5096676/5c0832c7-c60d-476b-a1ed-1e26c37f2408)

dc jack from diverses6 macro package;

![Untitled2](https://github.com/cdhigh/sprintFontRelease/assets/5096676/f8531ab4-d472-4212-a753-8ccfc6de3e58)

http://web.archive.org/web/20170514125216fw_/http://www.abacom-online.de/html/dateien/bibo_lay/diverses6.zip

http://web.archive.org/web/20170514125216fw_/http://www.abacom-online.de/html/dateien/bibo_lay/diverses5.zip


[hole.zip](https://github.com/cdhigh/sprintFontRelease/files/12337828/hole.zip)

**Comment by maksland** [comment]
Do they make a lot of holes in production or do they do it with a milling cutter ? Are the edges of the cut smooth ?
![hole](https://github.com/cdhigh/sprintFontRelease/assets/59772438/da19ecb9-ad73-4c04-aeee-813f06ee44bb)

**Comment by gevv** [comment]
Cut edges are smooth, no problems.

**Comment by maksland** [comment]
Are you planning other updates ?
I really liked your plugin !

**Comment by cdhigh** [comment]
No plan recently
