### ISSUE TITLE
sprintFont plugin startup error

### ISSUE THREAD

**Issue by griffin9k** [cdhigh/sprintFontRelease#6]
the error is as screenshot
![sprintfont ucrtbase dll err](https://github.com/cdhigh/sprintFontRelease/assets/52750376/c9272d5c-cf87-48c4-9075-30f079bbf787)

**Comment by cdhigh** [comment]
Reinstall vc runtime 2015?

**Comment by cdhigh** [comment]
Your os is windows XP?
this app not compatable with windows XP by now.

**Comment by cdhigh** [comment]
Release v1.5.3, added a package for windows XP.
https://github.com/cdhigh/sprintFontRelease/releases/tag/v1.5.3
![xp_scr](https://github.com/cdhigh/sprintFontRelease/assets/2580077/5ff5fe30-e12b-4f25-9066-68baaa8ed08a)

**Comment by griffin9k** [comment]
> Your os is windows XP? this app not compatable with windows XP by now.

it's Windows 7 64bit with Windows classic UI

**Comment by cdhigh** [comment]
Install vc runtime 2015 Will help

**Comment by griffin9k** [comment]
> Install vc runtime 2015 Will help

I've reinstalled VC++ 2015, the problem resolved, thx a lot.

**Comment by griffin9k** [comment]
The problem came up again with the same error message

**Comment by cdhigh** [comment]
Other software might have disrupted the dependency environment. It is recommended to directly search online and install a complete set of VC runtimes.

**Comment by griffin9k** [comment]
the list of vc++ installed
![捕获](https://github.com/cdhigh/sprintFontRelease/assets/52750376/c70258c5-4ae8-4dbb-87f7-52c455862344)

**Comment by cdhigh** [comment]
This is a system configuration issue, which is not related to sprintFont and will not be fixed.
